### ISSUE TITLE
after 1 dropdown it disable 

### ISSUE THREAD

**Issue by xalteropsx** [darrenburns/textual-autocomplete#2]
how can we re-enable it need multi dropdown

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/211147113-97482f3c-38cf-4d36-b47b-51e4d9886da7.png)
this really lol

**Comment by darrenburns** [comment]
The latest Textual release broke things for this lib - it should be fixed now.
